KinkyDungeonSpellListEnemies.push(
    //Bubble Turret Spells
    {
        enemySpell: true,
        name: "TurretShotBubble",
        tags: ["binding", "bolt", "offense"],
        sfx: "BubbleBlow",
        hitsfx: "BubbleHit",
        manacost: 4,
        components: [],
        level: 1,
        type: "bolt",
        projectileTargeting: true,
        onhit: "",
        power: 2,
        delay: 0,
        range: 10,
        damage: "soap",
        speed: 1,
        playerEffect: { name: "BubbleBullet", power: 3 }
    },



    {
        enemySpell: true,
        name: "EnemyBubbleSpread",
        color: "#88ffff",
        minRange: 0,
        landsfx: "Bubbling",
        effectTileDurationMod: 20, effectTileAoE: 1.5, effectTileDensity: 1,
        effectTile:
        {
            name: "Water",
            duration: 20,
        },
        manacost: 4,
        pecialCD: 12,
        components: ["Legs"],
        level: 1,
        type: "inert",
        onhit: "aoe",
        time: 3,
        delay: 1,
        power: 5,
        range: 6,
        size: 3,
        aoe: 1.5,
        lifetime: 1,
        damage: "acid",
        channel: 2,
        playerEffect: { name: "bubbling", power: 5 }
    },
    {
        enemySpell: true,
        name: "BubbleMinigun",
        castCondition: "B_Windup_Ready",
        bindType: "Soap",
        color: "#ffff00",
        minRange: 1.5,
        sfx: "MiniFire",
        manacost: 0,
        components: ["Arms"],
        shotgunCount: 2,
        shotgunDistance: 6,
        shotgunSpread: 1.5,
        shotgunSpeedBonus: 1.5,
        level: 1,
        type: "bolt",
        projectileTargeting: true,
        onhit: "",
        power: 1,
        time: 0,
        delay: 0,
        range: 20,
        damage: "acid",
        speed: 1.0,
        playerEffect: { name: "BubbleBullet", power: 1, }
    },
    {
        enemySpell: true,
        name: "BubbleMinigunWindup",
        castCondition: "B_Windup_Start",
        minRange: 1.5,
        tags: [],
        sfx: "MiniWind",
        school: "Any",
        anacost: 0,
        omponents: [],
        noise: 3,
        noTargetPlayer: true,
        mustTarget: true,
        level: 1,
        type: "special",
        onhit: "",
        special: "Windup",
        noSprite: true,
        evadeable: false,
        noblock: true,
        power: 0,
        time: 3,
        range: 20,
        size: 1,
        lifetime: 1,
        aoe: 0.5,
        damage: "inert",
    },
    {
        enemySpell: true,
        name: "WitchBlowBubble",
        hitsfx: "BubbleHit",
        sfx: "FireSpell",
        //tags: ["binding", "bolt", "offense"],
        school: "Conjure",
        manacost: 2,
        components: [],
        level: 1,
        type: "bolt",
        projectileTargeting: true,
        onhit: "",
        power: 2.5,
        delay: 0,
        noMiscast: true,
        events: [{ trigger: "bulletHitEnemy", type: "ApplyBubble", power: 1, duration: 8, damage: "stun" },],
        range: 12,
        speed: 0.8,
        damage: "acid",
        playerEffect: { name: "bubblehitted", power: 3 }
    },
    /*
    {
        enemySpell: true,
        name: "EnemyMagicBlowBubble",
        tags: ["binding", "bolt", "offense"],
        sfx: "BubbleBlow",
        hitsfx: "BubbleHit",
        manacost: 4,
        specialCD: 12,
        components: [],
        level: 1,
        type: "bolt",
        projectileTargeting: true,
        onhit: "",
        power: 2,
        delay: 0,
        range: 10,
        damage: "acid",
        speed: 0.6,
        playerEffect: { name: "magicbubblehitted", power: 5 }
    },
    */
    {
        enemySpell: true,
        name: "MagicSoapBubbleBurst",
        color: "#88ffff",
        minRange: 0,
        sfx: "Grope",
        landsfx: "RubberBolt",
        effectTileDurationMod: 10,
        effectTileAoE: 1.5,
        effectTileDensity: 0.5,
        effectTile: {
            name: "Water",
            duration: 20,
        },
        manacost: 4,
        specialCD: 12,
        components: ["Verbal"],
        level: 1,
        type: "inert",
        onhit: "aoe",
        time: 3,
        delay: 3,
        power: 5,
        range: 6,
        size: 3,
        aoe: 1.5,
        lifetime: 1,
        damage: "acid",
        channel: 2,
        playerEffect: { name: "magicbubblehitted", power: 5 }
    },
)