KinkyDungeonEnemies.push(
	{
		name: "BubbleTurret",
		playLine: "Robot",
		noChaseUnrestrained: true,
		nonDirectional: true,
		color: "#ff3367",
		tags: KDMapInit(["Elemental", "disarmimmune", "ignoreharmless", "mimicBlock", "doortrap", "robot", "acidweakness", "soulresist", "minor", "ranged", "electricsevereweakness", "coldresist", "iceresist", "slashresist", "crushsevereweakness", "pierceweakness"]),
		AI: "hunt",
		difficulty: 0.2,
		events: [
			{ trigger: "getLights", type: "enemyTorch", power: 4.5, color: "#ff5555" },
		],
		spells: ["TurretShotBubble", /*"EnemyMagicBlowBubble"*/],
		spellCooldownMult: 0.3,
		spellCooldownMod: 0,
		projectileTargeting: true,
		cueSfx: {
			Block: "Clang",
			Resist: "SoftShield",
			Damage: "RobotHit",
		},
		maxblock: 0,
		maxdodge: 0,
		Sound: {
			baseAmount: 0,
			moveAmount: 0,
			alertAmount: 12,
		},
		RestraintFilter: {
			unlimitedRestraints: true,
		},
		armor: 2.0, maxhp: 20, movePoints: 9999, immobile: true,
		visionRadius: 8, followRange: 999,
		sneakThreshold: 1,
		evasion: -9,
		attack: "SpellMeleeWill",
		attackPoints: 2,
		attackWidth: 1,
		attackRange: 1,
		power: 2,
		dmgType: "electric",
		minLevel: 0,
		weight: 3,
		terrainTags: { "secondhalf": 2, "thirdhalf": 1, "water": 9, "bubbleOptOut": -6, "bubblePref": 9, "elements": 5, },
		allFloors: true,
		shrines: ["Elements"],
		ondeath: [{ type: "spellOnSelf", spell: "EnemyBubbleSpread" }],
		dropTable: [{ name: "Gold", amountMin: 3, amountMax: 5, weight: 10 }, { name: "IMBubbleMachineGun", weight: 1, noSummon: true }]
	},

	{
		name: "BalloonStuffingMachine",
		color: "#2277ee",
		hitsfx: "Vacuumed",
		tags: KDMapInit(["BalloonCage", "ignoretiedup", "disarmimmune", "blindimmune", "minor", "melee", "acidweakness", "soulresist", "minor", "electricsevereweakness", "coldresist", "iceresist", "slashresist", "crushsevereweakness", "pierceweakness"]),
		noChaseUnrestrained: true,
		nonDirectional: true,
		AI: "hunt",
		immobile: true,
		visionRadius: 7,
		movePoints: 9999,
		blindSight: 999,
		maxhp: 30,
		minLevel: 0,
		weight: 2,
		attackPoints: 3,
		attack: "MeleeBindSuicideWill",
		suicideOnAdd: true,
		attackWidth: 6,
		attackRange: 1,
		power: 7,
		dmgType: "grope",
		Sound: {
			baseAmount: 0,
		},
		nopickpocket: true,
		terrainTags: { "secondhalf": 2, "thirdhalf": 1, "latexAnger": 10, "latexRage": 3, "latexPleased": 1.5, "latexFriendly": 2.2, "alchemist": 12, "Caldera": 10 },
		allFloors: true,
		shrines: ["Latex"],
		dropTable: [{ name: "Gold", amountMin: 3, amountMax: 100, weight: 10 }, { name: "AncientPowerSourceSpent", weight: 1, noSummon: true }]
	},

	{
		name: "MaidforceBMG",
		nameList: "russian",
		faction: "Maidforce",
		bound: "MaidforceMini",
		outfit: "MaidforceHeavy",
		style: "Maid",
		clusterWith: "maid",
		color: "#814BB7",
		playLine: "GunnerMaid",
		tags: KDMapInit(["leashing", "opendoors", "imprisonable", "tickleweakness", "human", "elite", "maid", "ranged", "maidRestraintsLight", "handcuffer", "gun", "jail", "jailer", "hunter"]),
		followLeashedOnly: true,
		followRange: 12,
		AI: "hunt",
		guardChance: 0.7,
		projectileAttack: true,
		evasion: -1.0,
		spells: ["BubbleMinigun", "BubbleMinigunWindup"],
		spellCooldownMult: 1,
		spellCooldownMod: 0,
		noKiteWhenHarmless: true,
		noSpellsWhenHarmless: true,
		armor: 1.0,
		stopToCast: true,
		events: [
			{ trigger: "tick", type: "secretToy" },
		],
		preferBlock: true,
		maxblock: 1,
		maxdodge: 0,
		sneakThreshold: 3, kite: 3.5, kiteChance: 0.75,
		visionRadius: 8, maxhp: 10, minLevel: 3, weight: -6, movePoints: 3.2, attackPoints: 4, attack: "SpellMeleeBindLock", attackWidth: 1, attackRange: 1, tilesMinRange: 1, power: 1,
		dmgType: "pain",
		fullBoundBonus: 4,
		terrainTags: {"secondhalf":2, "lastthird":-1, "open": 8, "illusionAnger": 9, "bubbleOptOut": -10, "bubblePref": 5, "illusionPleased": 9, "illusionFriendly": 5, "illusionRage": 3, "latexAnger": 3, "maid": 10},
		shrines: ["Illusion"],
		allFloors: true,
		weightMult: 0.5,
		attackLock: "White",
		dropTable: [{ name: "Gold", amountMin: 15, amountMax: 20, weight: 10 }, { name: "BubbleMachineGun", weight: 26, ignoreInInventory: true }]
	},

	{
		name: "WitchBubble",
		nameList: "witch",
		outfit: "WitchWater",
		style: "Water",
		faction: "Witch",
		clusterWith: "elemental",
		bound: "WitchWater",
		playLine: "Witch",
		color: "#4572e3",
		tags: KDMapInit(["leashing", "mage", "guardCall", "jailer", "opendoors", "imprisonable", "handcuffer", "water", "closedoors", "human", "witch", "ranged", "miniboss", "unflinching", "fireresist", "acidresist", "electricsevereweakness", "pierceresist", "hunter", "latexRestraints"]),
		followRange: 1,
		dontKiteWhenDisabled: true,
		kite: 2.5,
		castWhileMoving: true,
		spells: ["WitchBlowBubble", "EnemyCM1", "MagicSoapBubbleBurst"],
		unlockCommandLevel: 1,
		unlockCommandCD: 12,
		stopToCast: true,
		spellRdy: true,
		spellCooldownMult: 0.3,
		spellCooldownMod: 0.1,
		AI: "hunt",
		guardChance: 0.6,
		visionRadius: 7,
		maxhp: 20,
		minLevel: 3,
		weight: 2,
		movePoints: 3,
		attackPoints: 4,
		attack: "SpellMeleeBindLock",
		attackWidth: 1,
		attackRange: 1,
		power: 2,
		dmgType: "grope",
		fullBoundBonus: 3,
		terrainTags: { "secondhalf": 2, "lastthird": 1, "bubbleOptout": -5, "bubblePref": 5, "elementsAnger": 6, "tech": -4, "water": 4, "ice": 2 },
		allFloors: true,
		shrines: [],
		followLeashedOnly: true,
		attackLock: "White",
		stamina: 5,
		maxblock: 0,
		maxdodge: 0,
		dropTable: [{ name: "Gold", amountMin: 10, amountMax: 20, weight: 14, noSummon: true }, { name: "BubbleWand", weight: 26, ignoreInInventory: true }],
	},
	{
		name: "BubblerZombie",
		bound: "SamuraiZombie",
		style: "Zombie",
		outfit: "Zombie",
		playLine: "Zombie",
		clusterWith: "zombie",
		tags: KDMapInit(["leashing", "zombie", "zombieTrap", "melee", "elite", "ranged", "fireweakness", "unflinching", "ropeRestraints", "ropeRestraints2", "meleeweakness", "hunter"]),
		evasion: -1,
		armor: 1,
		followRange: 1,
		AI: "hunt",
		castWhileMoving: true,
		specialCD: 8, specialAttack: "Bind", specialRemove: "Lock", specialCDonAttack: true, strictAttackLOS: true, specialDamage: "soap",
		specialRange: 4, projectileTargeting: true, specialWidth: 1, ignoreStaminaForBinds: true, specialExtraTags: ["magicbubble"],
		/*
		stunTime: 2,
		specialCD: 6,
		specialAttack: "WillBind",
		specialPower: 5,
		specialDamage: "pain",
		attackLock: "White",
		specialExtraTags: "magicbubble",
		specialRemove: "Lock",
		*/
		Resistance: {
			block_phys: 2,
		},
		stamina: 2,
		//specialCDonAttack: false,
		visionRadius: 6,
		maxhp: 18,
		minLevel: 4,
		weight: 9,
		movePoints: 3,
		attackPoints: 3,
		attack: "MeleeBindLock",
		attackWidth: 1,
		attackRange: 1,
		power: 2,
		dmgType: "grope",
		fullBoundBonus: 3,
		specialWidth: 5,
		specialRange: 1,
		terrainTags: { "secondhalf": 5, "zombieTrap": 20, "lastthird": 5 },
		shrines: ["Will"],
		floors: KDMapInit(["grv", "tmb"]),
		dropTable: [{ name: "Gold", amountMin: 15, amountMax: 20, weight: 3.5 }, { name: "BubbleKatana", weight: 10, ignoreInInventory: true },]
	},


)