KinkyDungeonSpellListEnemies.push(
    //Bubble Turret Spells
    //to weapon
    {
        name: "shotbubble",

        hitsfx: "Shock",
        sfx: "Laser",

        school: "Conjure",
        manacost: 1,
        components: [],
        level: 1,
        type: "bolt",
        projectileTargeting: true,
        nonVolatile: true,
        onhit: "",
        power: 2.5,
        delay: 0,
        noMiscast: true,
        events: [{ trigger: "bulletHitEnemy", type: "ApplyBubble" },],

        range: 12,
        speed: 1,
        damage: "stun",
        playerEffect: { name: "bubblehitself", power: 3 }
    },


    {
        name: "PlayerBlowBubble",

        hitsfx: "BubbleHit",
        sfx: "HumanBubbleBlow",

        //tags: ["binding", "bolt", "offense"],
        school: "Conjure",
        manacost: 2,
        components: ["Verbal"],
        level: 1,
        type: "bolt",
        projectileTargeting: true,
        onhit: "",
        power: 2.5,
        delay: 0,
        noMiscast: true,
        events: [{ trigger: "bulletHitEnemy", type: "ApplyBubble", power: 1, duration: 8, damage: "stun" },],
        range: 8,
        speed: 0.7,
        playerEffect: { name: "bubblehitself", power: 3 }
    },

    {
        name: "GaggedBlowBubble",
        hitsfx: "BubbleHit",
        sfx: "HeavySwing",
        //tags: ["binding", "bolt", "offense"],
        school: "Conjure",
        manacost: 3,
        components: ["Arms"],
        level: 1,
        type: "bolt",
        projectileTargeting: true,
        onhit: "",
        power: 2.5,
        delay: 0,
        noMiscast: false,
        events: [{ trigger: "bulletHitEnemy", type: "ApplyBubble", power: 1, duration: 8, damage: "stun" },],
        range: 8,
        speed: 0.4,
        playerEffect: { name: "bubblehitself", power: 3 }
    },
    /*
    {
        enemySpell: true,
        name: "PlayerBubbleMinigun",
        castCondition: "reload",
        bindType: "Soap",
        color: "#ffff00",
        minRange: 1.5,
        sfx: "MiniFire",
        manacost: 0,
        components: ["Arms"],
        shotgunCount: 3,
        shotgunDistance: 6,
        shotgunSpread: 1.5,
        shotgunSpeedBonus: 1.5,
        level: 1,
        type: "bolt",
        projectileTargeting: true,
        onhit: "",
        power: 1,
        time: 0,
        delay: 0,
        range: 20,
        damage: "acid",
        speed: 1.0,
        playerEffect: { name: "BubbleBullet", power: 1, }
    },
    */
    {
        name: "PlayerBubbleMinigun",
        //tags: ["arrowreplace"],
        bindType: "Soap",
        color: "#88ff88",
        sfx: "MiniFire",
        manacost: 0,
        noMiscast: true,
        components: ["Arms"],
        shotgunCount: 4,
        shotgunDistance: 6,
        shotgunSpread: 1.5,
        shotgunSpeedBonus: 1.5,
        level: 1,
        type: "bolt",
        crit: 2.0,
        events: [{ trigger: "bulletHitEnemy", type: "ApplyBubbleBullet", power: 1, duration: 8, damage: "stun" },],
        faction: "Player",
        projectileTargeting: true,
        onhit: "",
        power: 1,
        delay: 0,
        range: 9,
        damage: "acid",
        speed: 1.0,
    },

    {
        name: "PlayerIMBubbleMinigun",
        //tags: ["arrowreplace"],
        bindType: "Soap",
        color: "#88ff88",
        sfx: "MiniFire",
        manacost: 0,
        noMiscast: true,
        components: ["Arms"],
        shotgunCount: 3,
        shotgunDistance: 6,
        shotgunSpread: 1.5,
        shotgunSpeedBonus: 1.5,
        level: 1,
        type: "bolt",
        crit: 2.0,
        events: [{ trigger: "bulletHitEnemy", type: "ApplyBubbleBullet", power: 1, duration: 8, damage: "stun" },],
        faction: "Player",
        projectileTargeting: true,
        onhit: "",
        power: 1,
        delay: 0,
        range: 9,
        damage: "acid",
        speed: 1.0,
    },
)
